In [31]:
import numpy as np
#python Lists
arr1 = list(range(1000000))
arr2 = list(range(1000000,2000000))

#Numpy arrays
arr1_np = np.array((arr1),dtype=np.int64)
arr2_np = np.array((arr2),dtype=np.int64)

In [32]:
%%time 
result = 0
for x1, x2 in zip(arr1, arr2) :
    result += x1*x2
result 

CPU times: total: 375 ms
Wall time: 387 ms


833332333333500000

In [33]:
%%time 
np.dot(arr1_np, arr2_np)

CPU times: total: 0 ns
Wall time: 3.42 ms


833332333333500000

In [34]:
arr_2d = np.array([[45, 67,87],
[45,12,61],
[104,64,35],
[68,9,731]], dtype = np.int64)

arr_2d.shape

(4, 3)

In [35]:
#3d array 

arr3d = np.array([
    [[1,2,3],[11,12,13]],
    [[21,22,23],[31,32,33]]
], dtype = np.int64)
arr3d.shape

(2, 2, 3)

In [36]:
arr3d.dtype

#If an array contains even a single floating point number, then ther entire type will be of float 

arr2d = np.array([[45, 67,87],
[45,12,61],
[104,64,35],
[68,9,7.31]])
arr_2d.dtype

dtype('int64')

In [37]:
weights = np.array([0.3,0.2,0.5])

#matmult function is used for matrix multiplication 

np.matmul(arr_2d,weights)



array([ 70.4,  46.4,  61.5, 387.7])

In [39]:
# another way to do matrix multiplication
arr_2d @ weights

array([ 70.4,  46.4,  61.5, 387.7])

In [41]:
#Array Indexing and slicing 
arr3d.shape

#grab a single element 
arr3d[1,1,2]

33

In [46]:
arr3d[1:]

# arr3d = np.array([
#     [[1,2,3],[11,12,13]],
#     [[21,22,23],[31,32,33]]
# ], dtype = np.int64)

#subarrays using ranges 
arr3d[1:, 0:1,:2] #end limit not included 

array([[[21, 22]]], dtype=int64)

In [48]:
arr1 = [[1,2],
[3,4.]]

arr2 = [[5,6,7],
[8,9,10]]

np.concatenate((arr1,arr2), axis=1)


array([[ 1.,  2.,  5.,  6.,  7.],
       [ 3.,  4.,  8.,  9., 10.]])

In [38]:
#working with csv files.

import urllib.request

urllib.request.urlretrieve(
    'https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')




('climate.txt', <http.client.HTTPMessage at 0x27dba2b7400>)